language: android
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
before_install:
# fix: License for package Android SDK Build-Tools 28.0.3 not accepted.
- yes | sdkmanager "build-tools;28.0.3"
- openssl aes-256-cbc -K $encrypted_c54f8e2b70b4_key -iv $encrypted_c54f8e2b70b4_iv -in playable_dept.jks.enc -out playable_dept.jks -d
script:
- true
deploy:
- provider: script
  skip_cleanup: true
  script: "./gradlew uploadReleaseToHockeyApp"
  on:
    branch: master